import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav & General
    home: 'Home',
    insurance: 'Insurance & Protection',
    roadside: 'Roadside Assistance',
    scrap: 'End-of-Life & Scrap',
    dashboard: 'Dashboard',
    profile: 'My Profile',
    requests: 'My Requests',
    vehicles: 'My Vehicles',
    quotes: 'My Quotes',
    invoices: 'My Invoices',
    get_quote: 'Get a Quote',
    sign_out: 'Sign Out',
    welcome: 'Welcome back to Garro',
    lang_toggle: 'العربية (RTL)',
    back_to_dashboard: "Back to Dashboard",
    edit: "Edit",
    delete: "Delete",
    status: "Status",
    actions: "Actions",
    details: "Details",
    loading: "Loading...",
    submit: "Submit",
    add: "Add",
    cancel: "Cancel",
    remove: "Remove",

    // Hero Home
    trusted_platform: "UAE's Trusted Car Service Platform",
    get_help: "Get Instant Help From Verified UAE Garages",
    hero_sub: "Emergency or regular service, we connect you with top-rated garages near you.",
    verified_garages: "Verified Garages",
    support: "Support",
    transparent: "Transparent",

    // Quote Form
    get_quotes_title: "Get Instant Quotes from Top-Rated Garages",
    quotes_sub: "Transparent pricing · Verified garages · Instant quotes",
    service_category: "Service Category",
    sub_category_label: "Sub-Category",
    brand: "Brand",
    model: "Model",
    year: "Year",
    city: "City",
    area_label: "Area",
    describe_issue: "Describe Your Issue",
    contact_info: "Contact Info",
    preferred_time: "Preferred Time",
    get_a_quote: "Get a Quote",
    select_category: "Select main category",
    select_subcategory: "Select sub-category",
    select_category_first: "Select main category first",
    select_brand_first: "Select Brand first",
    select_city_first: "Select City first",
    desc_placeholder: "Describe the issue",
    phone_placeholder: "Enter mobile number",
    select_time: "Select time",
    time_asap: "ASAP — Urgent",
    time_today: "Today",
    time_week: "This Week",
    time_flexible: "Flexible",

    // How It Works
    how_it_works: "How Garro Works",
    how_sub: "Simple steps to get your car back on track with trusted service.",
    step1_title: "Select Issue",
    step1_desc: "Tell us what your car needs.",
    step2_title: "We Search",
    step2_desc: "We find the best local garages.",
    step3_title: "Compare & Choose",
    step3_desc: "Compare prices & services.",
    step4_title: "Pick Up / Drop",
    step4_desc: "Book a slot & get your car serviced.",
    step5_title: "Track & Relax",
    step5_desc: "Live updates till your car is done.",
    get_quote_now: "Get a Quote Now",

    // Dark Stats
    stat_verified_uae: "Verified Garages Across UAE",
    stat_happy_served: "Happy Customers Served",
    stat_avg_response: "Average Response Time",
    stat_satisfaction: "Customer Satisfaction Rate",
    stat_emergency_support: "Emergency Support",

    // Profile Page
    profile_title: "My Account Profile",
    personal_info: "Personal Information",
    first_name: "First Name",
    last_name: "Last Name",
    email_readonly: "Email Address (Read-only)",
    phone_readonly: "Phone Number (Read-only)",
    save_profile_changes: "Save Profile Changes",
    change_pwd_title: "🔐 Change Account Password",
    change_pwd_desc: "Verification code will be sent to your email to confirm this action",
    current_pwd_label: "Current Account Password",
    current_pwd_placeholder: "Enter current password to request OTP",
    verify_send_otp: "Verify & Send OTP",
    enter_otp: "Enter 6-Digit Email OTP",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    new_pwd_placeholder: "Min 6 characters",
    confirm_pwd_placeholder: "Repeat new password",
    back: "Back",
    submit_pwd_change: "Confirm Password Change",
    updating: "Updating...",
    manage_fleet_title: "🚗 Manage Your Fleet",
    manage_fleet_desc: "Add your family cars or fleet vehicles here. You can select them easily when scheduling diagnostics, major services, or recovery requests.",
    security_alert_title: "⚠️ Security Protection",
    security_alert_desc: "For security, email and phone numbers cannot be changed directly. Toggling password changes requires OTP validation, and profiles lock for 30 minutes after 5 failed attempts.",
    demo_mode: "Demo Mode",
    use_code: "Use code",
    to_verify: "to verify",

    // Vehicles Page
    my_garage_title: "🚗 My Garage (Vehicles)",
    registered_vehicles: "Registered Vehicles",
    no_vehicles: "No vehicles registered yet. Add your first vehicle using the form on the right.",
    add_vehicle: "Add a Vehicle",
    brand_make: "Brand / Make",
    select_make: "Select Make",
    registration_plate: "Registration Plate",
    plate_placeholder: "e.g. Dubai A-12345",
    model_placeholder: "Select Model",
    year_placeholder: "Select Year",
    vin_placeholder: "17-digit Chassis Number",
    vin_optional: "VIN / Chassis (Optional)",
    adding_btn: "Adding Vehicle...",
    add_vehicle_btn: "Register Vehicle",
    remove_vehicle_btn: "Remove Vehicle",
    status_roadworthy: "Status: Roadworthy",

    // Requests Page
    my_service_requests: "My Service Requests",
    active_requests: "Active Requests",
    past_requests: "Past / Closed",
    all_requests: "All Requests",
    no_requests: "No service requests found.",
    request_id: "Request ID",
    date_submitted: "Date Submitted",
    garage_assigned: "Garage Assigned",
    helper_assigned: "Helper Assigned",
    track_service: "Track Service",
    unassigned: "Unassigned (Admin Review)",

    // Quotes Page
    my_service_quotes: "My Service Quotes",
    no_quotes: "No active service quotes found.",
    view_quote: "View Quote",
    approve: "Approve",
    reject: "Reject",
    total_price: "Total Price",
    vat_included: "VAT Included (5%)",
    quote_expires: "Expires In",
    expired: "Expired",
    spare_parts_cost: "Spare Parts Cost",
    labor_cost: "Labor / Repair Charges",
    aed: "AED",
    subtotal: "Subtotal",
    service_fee: "Service Fee (10%)",
    vat: "VAT (5%)",
    total_due: "Total Amount Due",
    reject_quote_btn: "Reject Quote",
    approve_quote_btn: "Approve Quote",
    request_details: "Request Details",
    quote_from: "Quote from",

    // Invoices Page
    my_service_invoices: "My Invoices & Payments",
    no_invoices: "No invoices found.",
    invoices_desc: "Download official UAE Tax Invoices and settle pending payments.",
    date: "Date",
    vehicle: "Vehicle",
    invoice_no: "Invoice No",
    amount: "Amount",
    due_date: "Due Date",
    pay_now: "Pay Now",
    download_invoice: "Download Invoice",
    payment_status: "Payment Status",
    paid: "Paid",
    unpaid: "Unpaid",

    // Footer
    footer_desc: "UAE's most trusted car help platform. Fast, reliable & certified car service across Dubai and all UAE emirates.",
    quick_links: "Quick Links",
    our_services: "Our Services",
    support_title: "Support",
    contact_us: "Contact Us",
    emergency_pickup: "Emergency Pickup",
    get_offers: "Get Offers & Updates",
    your_email: "Your email",
    subscribed_msg: "✓ Subscribed! Watch your inbox.",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2025 Garro · All rights reserved · UAE's Most Trusted Car Service Platform"
  },
  ar: {
    // Nav & General
    home: 'الرئيسية',
    insurance: 'التأمين والحماية',
    roadside: 'المساعدة على الطريق',
    scrap: 'نهاية العمر والخردة',
    dashboard: 'لوحة التحكم',
    profile: 'ملفي الشخصي',
    requests: 'طلباتي',
    vehicles: 'مركباتي',
    quotes: 'عروض الأسعار',
    invoices: 'فواتيري',
    get_quote: 'احصل على عرض سعر',
    sign_out: 'تسجيل الخروج',
    welcome: 'مرحباً بك في قارو',
    lang_toggle: 'English (LTR)',
    back_to_dashboard: "العودة للوحة التحكم",
    edit: "تعديل",
    delete: "حذف",
    status: "الحالة",
    actions: "الإجراءات",
    details: "التفاصيل",
    loading: "جاري التحميل...",
    submit: "إرسال",
    add: "إضافة",
    cancel: "إلغاء",
    remove: "إزالة",

    // Hero Home
    trusted_platform: "منصة صيانة السيارات الأكثر ثقة في الإمارات",
    get_help: "احصل على مساعدة فورية من كراجات الإمارات المعتمدة",
    hero_sub: "خدمات الطوارئ أو الخدمات الدورية، نصلك بأفضل الكراجات تقييماً بالقرب منك.",
    verified_garages: "كراج معتمد",
    support: "الدعم الفني",
    transparent: "شفافية تامة",

    // Quote Form
    get_quotes_title: "احصل على عروض أسعار فورية من كراجات ممتازة",
    quotes_sub: "أسعار شفافة · كراجات معتمدة · عروض أسعار فورية",
    service_category: "فئة الخدمة",
    sub_category_label: "الفئة الفرعية",
    brand: "الماركة",
    model: "الموديل",
    year: "السنة",
    city: "المدينة",
    area_label: "المنطقة",
    describe_issue: "وصف المشكلة",
    contact_info: "معلومات الاتصال",
    preferred_time: "الوقت المفضل",
    get_a_quote: "احصل على عرض سعر",
    select_category: "اختر الفئة الرئيسية",
    select_subcategory: "اختر الفئة الفرعية",
    select_category_first: "اختر الفئة الرئيسية أولاً",
    select_brand_first: "اختر الماركة أولاً",
    select_city_first: "اختر المدينة أولاً",
    desc_placeholder: "صف المشكلة هنا بالتفصيل...",
    phone_placeholder: "أدخل رقم الهاتف المحمول",
    select_time: "اختر الوقت",
    time_asap: "عاجل جداً — في أسرع وقت",
    time_today: "اليوم",
    time_week: "هذا الأسبوع",
    time_flexible: "وقت مرن / غير محدد",

    // How It Works
    how_it_works: "كيف يعمل قارو",
    how_sub: "خطوات بسيطة لإصلاح سيارتك وإعادتها للطريق بخدمات موثوقة.",
    step1_title: "اختر المشكلة",
    step1_desc: "أخبرنا بما تحتاجه سيارتك.",
    step2_title: "نحن نبحث",
    step2_desc: "نبحث عن أفضل الكراجات المحلية.",
    step3_title: "قارن واختر",
    step3_desc: "قارن بين الأسعار والخدمات.",
    step4_title: "الاستلام والتوصيل",
    step4_desc: "احجز موعداً واحصل على صيانة لسيارتك.",
    step5_title: "تتبع واسترخِ",
    step5_desc: "تحديثات مباشرة حتى الانتهاء من سيارتك.",
    get_quote_now: "احصل على عرض سعر الآن",

    // Dark Stats
    stat_verified_uae: "كراج معتمد في جميع أنحاء الإمارات",
    stat_happy_served: "عميل سعيد تم خدمتهم بنجاح",
    stat_avg_response: "متوسط وقت الاستجابة",
    stat_satisfaction: "معدل رضا العملاء",
    stat_emergency_support: "دعم الطوارئ على مدار الساعة",

    // Profile Page
    profile_title: "ملف الحساب الشخصي",
    personal_info: "المعلومات الشخصية",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    email_readonly: "البريد الإلكتروني (للقراءة فقط)",
    phone_readonly: "رقم الهاتف (للقراءة فقط)",
    save_profile_changes: "حفظ تغييرات الملف الشخصي",
    change_pwd_title: "🔐 تغيير كلمة مرور الحساب",
    change_pwd_desc: "سيتم إرسال رمز التحقق إلى بريدك الإلكتروني لتأكيد هذا الإجراء",
    current_pwd_label: "كلمة المرور الحالية للحساب",
    current_pwd_placeholder: "أدخل كلمة المرور الحالية لطلب رمز التحقق",
    verify_send_otp: "التحقق وإرسال الرمز",
    enter_otp: "أدخل رمز التحقق المكون من 6 أرقام",
    new_password: "كلمة المرور الجديدة",
    confirm_new_password: "تأكيد كلمة المرور الجديدة",
    new_pwd_placeholder: "6 أحرف كحد أدنى",
    confirm_pwd_placeholder: "أعد كتابة كلمة المرور الجديدة",
    back: "رجوع",
    submit_pwd_change: "تأكيد تغيير كلمة المرور",
    updating: "جاري التحديث...",
    manage_fleet_title: "🚗 إدارة أسطول سياراتك",
    manage_fleet_desc: "أضف سيارات عائلتك أو أسطول مركباتك هنا. يمكنك اختيارهم بسهولة عند حجز الفحص، أو الصيانة، أو طلبات السحب.",
    security_alert_title: "⚠️ حماية الأمان",
    security_alert_desc: "لدواعي أمنية، لا يمكن تغيير البريد الإلكتروني وأرقام الهواتف مباشرة. يتطلب تغيير كلمة المرور التحقق من رمز OTP، ويتم قفل الملف الشخصي لمدة 30 دقيقة بعد 5 محاولات فاشلة.",
    demo_mode: "وضع التجربة",
    use_code: "استخدم الرمز",
    to_verify: "للتحقق",

    // Vehicles Page
    my_garage_title: "🚗 كراجي (المركبات)",
    registered_vehicles: "المركبات المسجلة",
    no_vehicles: "لا توجد مركبات مسجلة بعد. أضف مركبتك الأولى باستخدام النموذج على اليمين.",
    add_vehicle: "إضافة مركبة",
    brand_make: "الماركة / المصنع",
    select_make: "اختر الماركة",
    registration_plate: "لوحة الترخيص",
    plate_placeholder: "مثال: دبي A-12345",
    model_placeholder: "اختر الموديل",
    year_placeholder: "اختر السنة",
    vin_placeholder: "رقم الشاسيه المكون من 17 خانة",
    vin_optional: "رقم الشاسيه / VIN (اختياري)",
    adding_btn: "جاري الإضافة...",
    add_vehicle_btn: "تسجيل المركبة",
    remove_vehicle_btn: "إزالة المركبة",
    status_roadworthy: "الحالة: جاهزة للاستخدام",

    // Requests Page
    my_service_requests: "طلبات الصيانة الخاصة بي",
    active_requests: "الطلبات النشطة",
    past_requests: "السابقة / المغلقة",
    all_requests: "كل الطلبات",
    no_requests: "لم يتم العثور على طلبات صيانة.",
    request_id: "رقم الطلب",
    date_submitted: "تاريخ تقديم الطلب",
    garage_assigned: "الكراج المعين",
    helper_assigned: "المساعد المعين",
    track_service: "تتبع الخدمة",
    unassigned: "لم يتم التعيين بعد (تحت المراجعة)",

    // Quotes Page
    my_service_quotes: "عروض أسعار الخدمة",
    no_quotes: "لم يتم العثور على عروض أسعار نشطة.",
    view_quote: "عرض السعر",
    approve: "موافقة",
    reject: "رفض",
    total_price: "السعر الإجمالي",
    vat_included: "شامل ضريبة القيمة المضافة (5%)",
    quote_expires: "ينتهي العرض خلال",
    expired: "منتهي الصلاحية",
    spare_parts_cost: "تكلفة قطع الغيار",
    labor_cost: "أجور العمالة / الإصلاح",
    aed: "د.إ",
    subtotal: "المجموع الفرعي",
    service_fee: "رسوم الخدمة (10%)",
    vat: "ضريبة القيمة المضافة (5%)",
    total_due: "إجمالي المبلغ المستحق",
    reject_quote_btn: "رفض عرض السعر",
    approve_quote_btn: "قبول عرض السعر",
    request_details: "تفاصيل الطلب",
    quote_from: "عرض سعر من",

    // Invoices Page
    my_service_invoices: "الفواتير والمدفوعات الخاصة بي",
    no_invoices: "لم يتم العثور على فواتير.",
    invoices_desc: "تحميل فواتير ضريبة دولة الإمارات الرسمية وتسوية المدفوعات المعلقة.",
    date: "التاريخ",
    vehicle: "المركبة",
    invoice_no: "رقم الفاتورة",
    amount: "القيمة",
    due_date: "تاريخ الاستحقاق",
    pay_now: "ادفع الآن",
    download_invoice: "تحميل الفاتورة",
    payment_status: "حالة الدفع",
    paid: "مدفوعة",
    unpaid: "غير مدفوعة",

    // Footer
    footer_desc: "منصة مساعدة السيارات الأكثر موثوقية في الإمارات. خدمة سيارات سريعة وموثوقة ومعتمدة في دبي وجميع إمارات الدولة.",
    quick_links: "روابط سريعة",
    our_services: "خدماتنا",
    support_title: "الدعم",
    contact_us: "اتصل بنا",
    emergency_pickup: "نقل طوارئ",
    get_offers: "احصل على العروض والتحديثات",
    your_email: "بريدك الإلكتروني",
    subscribed_msg: "✓ تم الاشتراك بنجاح! تابع صندوق الوارد.",
    privacy: "الخصوصية",
    terms: "الشروط",
    copyright: "© 2025 غارو · جميع الحقوق محفوظة · منصة خدمات السيارات الأكثر موثوقية في الإمارات"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
  };

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
