import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav & General
    home: "Home",
    insurance: "Insurance",
    roadside: "Roadside",
    scrap: "Scrap",
    dashboard: "Dashboard",
    customer_portal: "Customer Portal",
    admin_dashboard: "Admin Dashboard",
    profile: "Profile",
    requests: "Requests",
    vehicles: "Vehicles",
    get_quote: "Get Quote",
    our_services: "Services",
    find_garages: "Find Garages",
    nav_about: "About Us",
    contact_us: "Contact",
    quotes: 'My Quotes',
    invoices: 'My Invoices',
    sign_out: 'Sign Out',
    welcome: 'Welcome back to Garro',
    lang_toggle: 'العربية (RTL)',
    back_to_dashboard: "Back to Dashboard",
    edit: "Edit",
    delete: "Delete",
    status: "Status",
    actions: "Actions",
    details: "Details",
    loading: "Loading...",
    submit: "Submit",
    add: "Add",
    cancel: "Cancel",
    remove: "Remove",

    // Hero Home
    trusted_platform: "UAE's Trusted Car Service Platform",
    get_help: "Get Instant Help From Verified UAE Garages",
    hero_sub: "Emergency or regular service, we connect you with top-rated garages near you.",
    verified_garages: "Verified Garages",
    support: "Support",
    transparent: "Transparent",

    // Quote Form
    get_quotes_title: "Get Instant Quotes from Top-Rated Garages",
    quotes_sub: "Transparent pricing · Verified garages · Instant quotes",
    service_category: "Service Category",
    sub_category_label: "Sub-Category",
    brand: "Brand",
    model: "Model",
    year: "Year",
    city: "City",
    area_label: "Area",
    describe_issue: "Describe Your Issue",
    contact_info: "Contact Info",
    preferred_time: "Preferred Time",
    get_a_quote: "Get a Quote",
    select_category: "Select main category",
    select_subcategory: "Select sub-category",
    select_category_first: "Select main category first",
    select_brand_first: "Select Brand first",
    select_city_first: "Select City first",
    desc_placeholder: "Describe the issue",
    phone_placeholder: "Enter mobile number",
    select_time: "Select time",
    time_asap: "ASAP — Urgent",
    time_today: "Today",
    time_week: "This Week",
    time_flexible: "Flexible",

    // How It Works
    how_it_works: "How Garro Works",
    how_sub: "Simple steps to get your car back on track with trusted service.",
    step1_title: "Select Issue",
    step1_desc: "Tell us what your car needs.",
    step2_title: "We Search",
    step2_desc: "We find the best local garages.",
    step3_title: "Compare & Choose",
    step3_desc: "Compare prices & services.",
    step4_title: "Pick Up / Drop",
    step4_desc: "Book a slot & get your car serviced.",
    step5_title: "Track & Relax",
    step5_desc: "Live updates till your car is done.",
    get_quote_now: "Get a Quote Now",

    // Dark Stats
    stat_verified_uae: "Verified Garages Across UAE",
    stat_happy_served: "Happy Customers Served",
    stat_avg_response: "Average Response Time",
    stat_satisfaction: "Customer Satisfaction Rate",
    stat_emergency_support: "Emergency Support",

    // Profile Page
    profile_title: "My Account Profile",
    personal_info: "Personal Information",
    first_name: "First Name",
    last_name: "Last Name",
    email_readonly: "Email Address",
    phone_readonly: "Phone Number",
    save_profile_changes: "Save Profile Changes",
    change_pwd_title: "Change Account Password",
    change_pwd_desc: "Verification code will be sent to your email to confirm this action",
    current_pwd_label: "Current Account Password",
    current_pwd_placeholder: "Enter current password to request OTP",
    verify_send_otp: "Verify & Send OTP",
    enter_otp: "Enter 6-Digit Email OTP",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    new_pwd_placeholder: "Min 6 characters",
    confirm_pwd_placeholder: "Repeat new password",
    back: "Back",
    submit_pwd_change: "Confirm Password Change",
    updating: "Updating...",
    manage_fleet_title: "Manage Your Fleet",
    manage_fleet_desc: "Add your family cars or fleet vehicles here. You can select them easily when scheduling diagnostics, major services, or recovery requests.",
    security_alert_title: "Security Protection",
    security_alert_desc: "For security, email and phone numbers cannot be changed directly. Toggling password changes requires OTP validation, and profiles lock for 30 minutes after 5 failed attempts.",
    demo_mode: "Demo Mode",
    use_code: "Use code",
    to_verify: "to verify",

    // Vehicles Page
    my_garage_title: "My Garage (Vehicles)",
    registered_vehicles: "Registered Vehicles",
    no_vehicles: "No vehicles registered yet. Add your first vehicle using the form on the right.",
    add_vehicle: "Add a Vehicle",
    brand_make: "Brand / Make",
    select_make: "Select Make",
    registration_plate: "Registration Plate",
    plate_placeholder: "e.g. Dubai A-12345",
    model_placeholder: "Select Model",
    year_placeholder: "Select Year",
    vin_placeholder: "17-digit Chassis Number",
    vin_optional: "VIN / Chassis (Optional)",
    adding_btn: "Adding Vehicle...",
    add_vehicle_btn: "Register Vehicle",
    remove_vehicle_btn: "Remove Vehicle",
    status_roadworthy: "Status: Roadworthy",

    // Requests Page
    my_service_requests: "My Service Requests",
    my_requests_sub: "Track and manage your active bookings, quotes, and service history.",
    active_requests: "Active Requests",
    past_requests: "Past / Closed",
    all_requests: "All Requests",
    no_requests: "No service requests found.",
    request_id: "Request ID",
    date_submitted: "Date Submitted",
    garage_assigned: "Garage Assigned",
    helper_assigned: "Helper Assigned",
    track_service: "Track Service",
    unassigned: "Unassigned (Admin Review)",

    // Quotes Page
    my_service_quotes: "My Service Quotes",
    no_quotes: "No active service quotes found.",
    view_quote: "View Quote",
    approve: "Approve",
    reject: "Reject",
    total_price: "Total Price",
    vat_included: "VAT Included (5%)",
    quote_expires: "Expires In",
    expired: "Expired",
    spare_parts_cost: "Spare Parts Cost",
    labor_cost: "Labor / Repair Charges",
    aed: "AED",
    subtotal: "Subtotal",
    service_fee: "Service Fee (10%)",
    vat: "VAT (5%)",
    total_due: "Total Amount Due",
    reject_quote_btn: "Reject Quote",
    approve_quote_btn: "Approve Quote",
    request_details: "Request Details",
    quote_from: "Quote from",

    // Invoices Page
    my_service_invoices: "My Invoices & Payments",
    no_invoices: "No invoices found.",
    invoices_desc: "Download official UAE Tax Invoices and settle pending payments.",
    date: "Date",
    vehicle: "Vehicle",
    invoice_no: "Invoice No",
    amount: "Amount",
    due_date: "Due Date",
    pay_now: "Pay Now",
    download_invoice: "Download Invoice",
    payment_status: "Payment Status",
    paid: "Paid",
    unpaid: "Unpaid",

    // Footer
    footer_desc: "UAE's most trusted car help platform. Fast, reliable & certified car service across Dubai and all UAE emirates.",
    quick_links: "Quick Links",
    support_title: "Support",
    emergency_pickup: "Emergency Pickup",
    get_offers: "Get Offers & Updates",
    your_email: "Your email",
    subscribed_msg: "✓ Subscribed! Watch your inbox.",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2025 Garro · All rights reserved · UAE's Most Trusted Car Service Platform",
    // Admin Sidebar & General
    overview: 'Overview',
    operations: 'Operations',
    manage_garages: 'Manage Garages',
    system_catalog: 'System Catalog',
    quote_builder: 'Quote Builder',
    customer_search: 'Customer Search',
    complaints: 'Complaints',
    reports_analytics: "Reports & Analytics",
    system_settings: 'System Settings',
    bookings: 'Bookings',
    people: 'People',
    all_users: 'All Users',
    staff_view: 'Staff View',
    manage_staff: 'Manage Staff',
    back_to_site: 'Back to Site',

    // Support Chat Inbox
    support_inbox: "Customer Support Inbox",
    support_inbox_desc: "View and reply to incoming messages and inquiries from customers in real-time",
    search_customer_placeholder: "Search customer name or email...",
    conversations_title: "Conversations",
    loading_conversations: "Loading conversations...",
    no_support_threads: "No support threads found.",
    no_messages_yet: "No messages yet",
    close_conversation: "Close conversation",
    loading_chat_logs: "Loading chat logs...",
    no_messages_in_convo: "No messages in this conversation.",
    type_reply_placeholder: "Type a reply...",
    support_chat_room: "Support Chat Room",
    select_thread_desc: "Select a customer thread from the sidebar console to start replying and resolving support queries in real-time.",
    // Garage Management
    manage_partner_garages: 'Manage Partner Garages',
    register_configure_workshops: 'Register and configure service partner workshops',
    add_new_garage: 'Add New Garage',
    total_garages: 'Total Garages',
    active_partners: 'Active Partners',
    suspended_inactive: 'Suspended/Inactive',
    avg_commission: 'Average Commission',
    workshop_name: 'Workshop Name',
    contact: 'Contact',
    areas_covered: 'Areas Covered',
    rating: 'Rating',
    commission: 'Commission',
    active: 'Active',
    inactive: 'Inactive',
    toggle_active: 'Toggle Active',
    // New Admin & Staff Dashboard Keys
    active_garages: 'Active Garages',
    todays_bookings: "Today's Bookings",
    completed: 'Completed',
    pending: 'Pending',
    month_revenue: 'Month Revenue',
    this_week: 'this week',
    registered_users: 'Registered Users',
    helper_staff: 'Helper Staff',
    avg_rating: 'Average Rating',
    new_reviews: 'New Reviews',
    unread_alerts: 'Unread Alerts',
    monthly_bookings_revenue: 'Monthly Bookings & Revenue',
    booking_status_dist: 'Booking Status Distribution',
    system_catalog_settings: 'System Catalog Settings',
    manage_metadata_catalogs: 'Manage metadata catalogs for vehicles brands, services, and coverage zones',
    brands: 'Brands',
    models: 'Models',
    categories: 'Categories',
    areas: 'Areas',
    import_csv: 'Import CSV',
    staff_management: 'Staff Management',
    staff_members_manage: 'staff members · Manage accounts and scheduling',
    create_account_directly: 'Create Account Directly',
    dashboard_back: 'Dashboard',
    current_staff: 'Current Staff',
    schedule: 'Schedule',
    deactivate: 'Deactivate',
    invite_new_helper: 'Invite New Helper',
    send_invitation_link: 'Send Invitation Link',
    recent_invitations: 'Recent Invitations',
    add_new_helper: 'Add New Helper / Staff Account',
    create_internal_credentials: 'Create internal credentials for field helpers or operations staff',
    email_address: 'Email Address',
    phone_number: 'Phone Number',
    select_role: 'Select Role',
    password: 'Password',
    internal_notes: 'Internal Notes',
    create_staff_account: 'Create Staff Account',
    staff_dashboard: 'Staff Dashboard',
    welcome_back: 'Welcome back',
    my_work: 'My Work',
    my_dashboard: 'My Dashboard',
    all_bookings: 'All Bookings',
    full_dashboard: 'Full Dashboard',
    my_bookings: 'My Bookings',
    today: 'Today',
    messages: 'Messages',
    todays_schedule: "Today's Schedule",
    active_jobs: 'Active Jobs',
    jobs_assigned: 'jobs assigned',
    pickup_required: 'Pickup Required'
  },
  ar: {
    // Nav & General
    home: "الرئيسية",
    insurance: "تأمين",
    roadside: "الطريق",
    scrap: "سكراب",
    dashboard: "لوحة التحكم",
    customer_portal: "بوابة العملاء",
    admin_dashboard: "لوحة تحكم المسؤول",
    profile: "الملف الشخصي",
    requests: "الطلبات",
    vehicles: "مركباتي",
    get_quote: "طلب تسعير",
    our_services: "خدماتنا",
    find_garages: "البحث عن كراجات",
    nav_about: "من نحن",
    contact_us: "اتصل بنا",
    quotes: 'عروض الأسعار',
    invoices: 'فواتيري',
    sign_out: 'تسجيل الخروج',
    welcome: 'مرحباً بك في قارو',
    lang_toggle: 'English (LTR)',
    back_to_dashboard: "العودة للوحة التحكم",
    edit: "تعديل",
    delete: "حذف",
    status: "الحالة",
    actions: "الإجراءات",
    details: "التفاصيل",
    loading: "جاري التحميل...",
    submit: "إرسال",
    add: "إضافة",
    cancel: "إلغاء",
    remove: "إزالة",

    // Hero Home
    trusted_platform: "منصة صيانة السيارات الأكثر ثقة في الإمارات",
    get_help: "احصل على مساعدة فورية من كراجات الإمارات المعتمدة",
    hero_sub: "خدمات الطوارئ أو الخدمات الدورية، نصلك بأفضل الكراجات تقييماً بالقرب منك.",
    verified_garages: "كراج معتمد",
    support: "الدعم الفني",
    transparent: "شفافية تامة",

    // Quote Form
    get_quotes_title: "احصل على عروض أسعار فورية من كراجات ممتازة",
    quotes_sub: "أسعار شفافة · كراجات معتمدة · عروض أسعار فورية",
    service_category: "فئة الخدمة",
    sub_category_label: "الفئة الفرعية",
    brand: "الماركة",
    model: "الموديل",
    year: "السنة",
    city: "المدينة",
    area_label: "المنطقة",
    describe_issue: "وصف المشكلة",
    contact_info: "معلومات الاتصال",
    preferred_time: "الوقت المفضل",
    get_a_quote: "احصل على عرض سعر",
    select_category: "اختر الفئة الرئيسية",
    select_subcategory: "اختر الفئة الفرعية",
    select_category_first: "اختر الفئة الرئيسية أولاً",
    select_brand_first: "اختر الماركة أولاً",
    select_city_first: "اختر المدينة أولاً",
    desc_placeholder: "صف المشكلة هنا بالتفصيل...",
    phone_placeholder: "أدخل رقم الهاتف المحمول",
    select_time: "اختر الوقت",
    time_asap: "عاجل جداً — في أسرع وقت",
    time_today: "اليوم",
    time_week: "هذا الأسبوع",
    time_flexible: "وقت مرن / غير محدد",

    // How It Works
    how_it_works: "كيف يعمل قارو",
    how_sub: "خطوات بسيطة لإصلاح سيارتك وإعادتها للطريق بخدمات موثوقة.",
    step1_title: "اختر المشكلة",
    step1_desc: "أخبرنا بما تحتاجه سيارتك.",
    step2_title: "نحن نبحث",
    step2_desc: "نبحث عن أفضل الكراجات المحلية.",
    step3_title: "قارن واختر",
    step3_desc: "قارن بين الأسعار والخدمات.",
    step4_title: "الاستلام والتوصيل",
    step4_desc: "احجز موعداً واحصل على صيانة لسيارتك.",
    step5_title: "تتبع واسترخِ",
    step5_desc: "تحديثات مباشرة حتى الانتهاء من سيارتك.",
    get_quote_now: "احصل على عرض سعر الآن",

    // Dark Stats
    stat_verified_uae: "كراج معتمد في جميع أنحاء الإمارات",
    stat_happy_served: "عميل سعيد تم خدمتهم بنجاح",
    stat_avg_response: "متوسط وقت الاستجابة",
    stat_satisfaction: "معدل رضا العملاء",
    stat_emergency_support: "دعم الطوارئ على مدار الساعة",

    // Profile Page
    profile_title: "ملف الحساب الشخصي",
    personal_info: "المعلومات الشخصية",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    email_readonly: "البريد الإلكتروني",
    phone_readonly: "رقم الهاتف",
    save_profile_changes: "حفظ تغييرات الملف الشخصي",
    change_pwd_title: "تغيير كلمة مرور الحساب",
    change_pwd_desc: "سيتم إرسال رمز التحقق إلى بريدك الإلكتروني لتأكيد هذا الإجراء",
    current_pwd_label: "كلمة المرور الحالية للحساب",
    current_pwd_placeholder: "أدخل كلمة المرور الحالية لطلب رمز التحقق",
    verify_send_otp: "التحقق وإرسال الرمز",
    enter_otp: "أدخل رمز التحقق المكون من 6 أرقام",
    new_password: "كلمة المرور الجديدة",
    confirm_new_password: "تأكيد كلمة المرور الجديدة",
    new_pwd_placeholder: "6 أحرف كحد أدنى",
    confirm_pwd_placeholder: "أعد كتابة كلمة المرور الجديدة",
    back: "رجوع",
    submit_pwd_change: "تأكيد تغيير كلمة المرور",
    updating: "جاري التحديث...",
    manage_fleet_title: "إدارة أسطول سياراتك",
    manage_fleet_desc: "أضف سيارات عائلتك أو أسطول مركباتك هنا. يمكنك اختيارهم بسهولة عند حجز الفحص، أو الصيانة، أو طلبات السحب.",
    security_alert_title: "حماية الأمان",
    security_alert_desc: "لدواعي أمنية، لا يمكن تغيير البريد الإلكتروني وأرقام الهواتف مباشرة. يتطلب تغيير كلمة المرور التحقق من رمز OTP، ويتم قفل الملف الشخصي لمدة 30 دقيقة بعد 5 محاولات فاشلة.",
    demo_mode: "وضع التجربة",
    use_code: "استخدم الرمز",
    to_verify: "للتحقق",

    // Vehicles Page
    my_garage_title: "كراجي (المركبات)",
    registered_vehicles: "المركبات المسجلة",
    no_vehicles: "لا توجد مركبات مسجلة بعد. أضف مركبتك الأولى باستخدام النموذج على اليمين.",
    add_vehicle: "إضافة مركبة",
    brand_make: "الماركة / المصنع",
    select_make: "اختر الماركة",
    registration_plate: "لوحة الترخيص",
    plate_placeholder: "مثال: دبي A-12345",
    model_placeholder: "اختر الموديل",
    year_placeholder: "اختر السنة",
    vin_placeholder: "رقم الشاسيه المكون من 17 خانة",
    vin_optional: "رقم الشاسيه / VIN (اختياري)",
    adding_btn: "جاري الإضافة...",
    add_vehicle_btn: "تسجيل المركبة",
    remove_vehicle_btn: "إزالة المركبة",
    status_roadworthy: "الحالة: جاهزة للاستخدام",

    // Requests Page
    my_service_requests: "طلبات الصيانة الخاصة بي",
    my_requests_sub: "تتبع وإدارة حجوزاتك النشطة، وعروض الأسعار، وسجل الصيانة.",
    active_requests: "الطلبات النشطة",
    past_requests: "السابقة / المغلقة",
    all_requests: "كل الطلبات",
    no_requests: "لم يتم العثور على طلبات صيانة.",
    request_id: "رقم الطلب",
    date_submitted: "تاريخ تقديم الطلب",
    garage_assigned: "الكراج المعين",
    helper_assigned: "المساعد المعين",
    track_service: "تتبع الخدمة",
    unassigned: "لم يتم التعيين بعد (تحت المراجعة)",

    // Quotes Page
    my_service_quotes: "عروض أسعار الخدمة",
    no_quotes: "لم يتم العثور على عروض أسعار نشطة.",
    view_quote: "عرض السعر",
    approve: "موافقة",
    reject: "رفض",
    total_price: "السعر الإجمالي",
    vat_included: "شامل ضريبة القيمة المضافة (5%)",
    quote_expires: "ينتهي العرض خلال",
    expired: "منتهي الصلاحية",
    spare_parts_cost: "تكلفة قطع الغيار",
    labor_cost: "أجور العمالة / الإصلاح",
    aed: "د.إ",
    subtotal: "المجموع الفرعي",
    service_fee: "رسوم الخدمة (10%)",
    vat: "ضريبة القيمة المضافة (5%)",
    total_due: "إجمالي المبلغ المستحق",
    reject_quote_btn: "رفض عرض السعر",
    approve_quote_btn: "قبول عرض السعر",
    request_details: "تفاصيل الطلب",
    quote_from: "عرض سعر من",

    // Invoices Page
    my_service_invoices: "الفواتير والمدفوعات الخاصة بي",
    no_invoices: "لم يتم العثور على فواتير.",
    invoices_desc: "تحميل فواتير ضريبة دولة الإمارات الرسمية وتسوية المدفوعات المعلقة.",
    date: "التاريخ",
    vehicle: "المركبة",
    invoice_no: "رقم الفاتورة",
    amount: "القيمة",
    due_date: "تاريخ الاستحقاق",
    pay_now: "ادفع الآن",
    download_invoice: "تحميل الفاتورة",
    payment_status: "حالة الدفع",
    paid: "مدفوعة",
    unpaid: "غير مدفوعة",

    // Footer
    footer_desc: "منصة مساعدة السيارات الأكثر موثوقية في الإمارات. خدمة سيارات سريعة وموثوقة ومعتمدة في دبي وجميع إمارات الدولة.",
    quick_links: "روابط سريعة",
    support_title: "الدعم",
    emergency_pickup: "نقل طوارئ",
    get_offers: "احصل على العروض والتحديثات",
    your_email: "بريدك الإلكتروني",
    subscribed_msg: "✓ تم الاشتراك بنجاح! تابع صندوق الوارد.",
    privacy: "الخصوصية",
    terms: "الشروط",
    copyright: "© 2025 غارو · جميع الحقوق محفوظة · منصة خدمات السيارات الأكثر موثوقية في الإمارات",
    // Admin Sidebar & General
    overview: 'نظرة عامة',
    operations: 'العمليات',
    manage_garages: 'إدارة الكراجات',
    system_catalog: 'دليل النظام',
    quote_builder: 'منشئ عروض الأسعار',
    customer_search: 'بحث العملاء',
    complaints: 'الشكاوى',
    reports_analytics: "التقارير والتحليلات",
    system_settings: 'إعدادات النظام',
    bookings: 'الحجوزات',
    people: 'الأشخاص',
    all_users: 'جميع المستخدمين',
    staff_view: 'عرض الموظفين',
    manage_staff: 'إدارة الموظفين',
    back_to_site: 'العودة للموقع',

    // Support Chat Inbox
    support_inbox: "صندوق وارد الدعم الفني",
    support_inbox_desc: "عرض والرد على الرسائل والاستفسارات الواردة من العملاء في الوقت الفعلي",
    search_customer_placeholder: "البحث بالاسم أو البريد الإلكتروني...",
    conversations_title: "المحادثات",
    loading_conversations: "جاري تحميل المحادثات...",
    no_support_threads: "لم يتم العثور على محادثات دعم.",
    no_messages_yet: "لا توجد رسائل بعد",
    close_conversation: "إغلاق المحادثة",
    loading_chat_logs: "جاري تحميل سجل المحادثة...",
    no_messages_in_convo: "لا توجد رسائل في هذه المحادثة.",
    type_reply_placeholder: "اكتب ردًا...",
    support_chat_room: "غرفة محادثة الدعم",
    select_thread_desc: "اختر محادثة عميل من القائمة الجانبية لبدء الرد وحل استفسارات الدعم الفني في الوقت الفعلي.",
    active: 'نشط',
    inactive: 'غير نشط',
    toggle_active: 'تغيير الحالة',
    // New Admin & Staff Dashboard Keys
    active_garages: 'الكراجات النشطة',
    todays_bookings: 'حجوزات اليوم',
    completed: 'مكتملة',
    pending: 'قيد الانتظار',
    month_revenue: 'إيرادات الشهر',
    this_week: 'هذا الأسبوع',
    registered_users: 'المستخدمين المسجلين',
    helper_staff: 'موظفي المساعدة',
    avg_rating: 'متوسط التقييم',
    new_reviews: 'مراجعات جديدة',
    unread_alerts: 'تنبيهات غير مقروءة',
    monthly_bookings_revenue: 'الحجوزات والإيرادات الشهرية',
    booking_status_dist: 'توزيع حالة الحجوزات',
    system_catalog_settings: 'إعدادات دليل النظام',
    manage_metadata_catalogs: 'إدارة أدلة البيانات الوصفية لماركات السيارات، الخدمات، ومناطق التغطية',
    brands: 'الماركات',
    models: 'الموديلات',
    categories: 'الفئات',
    areas: 'المناطق',
    import_csv: 'استيراد CSV',
    staff_management: 'إدارة الموظفين',
    staff_members_manage: 'موظفين · إدارة الحسابات والجدولة',
    create_account_directly: 'إنشاء حساب مباشرة',
    dashboard_back: 'لوحة التحكم',
    current_staff: 'الموظفين الحاليين',
    schedule: 'الجدولة',
    deactivate: 'تعطيل',
    invite_new_helper: 'دعوة مساعد جديد',
    send_invitation_link: 'إرسال رابط الدعوة',
    recent_invitations: 'الدعوات الأخيرة',
    add_new_helper: 'إضافة حساب مساعد / موظف جديد',
    create_internal_credentials: 'إنشاء بيانات اعتماد داخلية للمساعدين الميدانيين أو موظفي العمليات',
    email_address: 'البريد الإلكتروني',
    phone_number: 'رقم الهاتف',
    select_role: 'اختر الدور',
    password: 'كلمة المرور',
    internal_notes: 'ملاحظات داخلية',
    create_staff_account: 'إنشاء حساب الموظف',
    staff_dashboard: 'لوحة تحكم الموظف',
    welcome_back: 'مرحباً بعودتك',
    my_work: 'عملي',
    my_dashboard: 'لوحة تحكمي',
    all_bookings: 'جميع الحجوزات',
    full_dashboard: 'لوحة التحكم الكاملة',
    my_bookings: 'حجوزاتي',
    today: 'اليوم',
    messages: 'الرسائل',
    todays_schedule: 'جدول اليوم',
    active_jobs: 'المهام النشطة',
    jobs_assigned: 'مهام مسندة',
    pickup_required: 'مطلوب استلام'
  },
  ur: {
    // Nav & General
    home: 'ہوم',
    insurance: 'انشورنس اور تحفظ',
    roadside: 'سڑک کنارے مدد',
    scrap: 'سکریپ کار سروس',
    dashboard: 'ڈیش بورڈ',
    customer_portal: 'کسٹمر پورٹل',
    admin_dashboard: 'ایڈمن ڈیش بورڈ',
    profile: 'میرا پروفائل',
    requests: 'میری درخواستیں',
    vehicles: 'میری گاڑیاں',
    quotes: 'کوٹیشنز',
    invoices: 'میرے انوائسز',
    get_quote: 'قیمت معلوم کریں',
    sign_out: 'سائن آؤٹ',
    welcome: 'گارو میں خوش آمدید',
    lang_toggle: 'English (LTR)',
    back_to_dashboard: "ڈیش بورڈ پر واپس جائیں",
    edit: "ترمیم",
    delete: "حذف کریں",
    status: "حالت",
    actions: "اقدامات",
    details: "تفصیلات",
    loading: "لوڈ ہو رہا ہے...",
    submit: "جمع کریں",
    add: "شامل کریں",
    cancel: "منسوخ کریں",
    remove: "خارج کریں",
    // Admin Sidebar & General
    overview: 'جائزہ',
    operations: 'آپریشنز',
    manage_garages: 'گیراج مینیج کریں',
    find_garages: 'گیراج تلاش کریں',
    system_catalog: 'سستم کیٹلاگ',
    quote_builder: 'کوٹ بلڈر',
    customer_search: 'گاہک تلاش کریں',
    complaints: 'شکایات',
    support: "سپورٹ",
    reports_analytics: "رپورٹس اور تجزیات",
    system_settings: 'سسٹم کی ترتیبات',
    bookings: 'بکنگز',
    people: 'لوگ',
    all_users: 'تمام صارفین',
    staff_view: 'اسٹاف ویو',
    manage_staff: 'اسٹاف مینیج کریں',
    back_to_site: 'سائٹ پر واپس جائیں',

    // Support Chat Inbox
    support_inbox: "کسٹمر سپورٹ ان باکس",
    support_inbox_desc: "حقیقی وقت میں صارفین سے موصولہ پیغامات اور پوچھ گچھ دیکھیں اور ان کا جواب دیں",
    search_customer_placeholder: "صارف کا نام یا ای میل تلاش کریں...",
    conversations_title: "محادثات",
    loading_conversations: "محادثات لوڈ ہو رہی ہیں...",
    no_support_threads: "کوئی سپورٹ بات چیت نہیں ملی۔",
    no_messages_yet: "ابھی تک کوئی پیغامات نہیں ہیں",
    close_conversation: "گفتگو بند کریں",
    loading_chat_logs: "چیٹ لاگز لوڈ ہو رہے ہیں...",
    no_messages_in_convo: "اس گفتگو میں کوئی پیغامات نہیں ہیں۔",
    type_reply_placeholder: "جواب لکھیں...",
    support_chat_room: "سپورٹ چیٹ روم",
    select_thread_desc: "صارفین کے پیغامات کا جواب دینے اور سپورٹ کے مسائل کو حقیقی وقت میں حل کرنے کے لیے سائڈبار کنسول سے ایک تھریڈ منتخب کریں۔",
    // Garage Management
    manage_partner_garages: 'پارٹنر گیراجز مینیج کریں',
    register_configure_workshops: 'سروس پارٹنر ورکشاپس کو رجسٹر اور کنفیگر کریں',
    add_new_garage: 'نیا گیراج شامل کریں',
    total_garages: 'کل گیراجز',
    active_partners: 'فعال پارٹنرز',
    suspended_inactive: 'معطل / غیر فعال',
    avg_commission: 'اوسط کمیشن',
    workshop_name: 'ورکشاپ کا نام',
    contact: 'رابطہ',
    areas_covered: 'احاطہ شدہ علاقے',
    rating: 'درجہ بندی',
    commission: 'کمیشن',
    active: 'فعال',
    inactive: 'غیر فعال',
    toggle_active: 'حالت تبدیل کریں',
    // New Admin & Staff Dashboard Keys
    active_garages: 'فعال گیراجز',
    todays_bookings: 'آج کی بکنگز',
    completed: 'مکمل',
    pending: 'معلق',
    month_revenue: 'ماہانہ آمدنی',
    this_week: 'اس ہفتے',
    registered_users: 'رجسٹرڈ صارفین',
    helper_staff: 'مددگار اسٹاف',
    avg_rating: 'اوسط درجہ بندی',
    new_reviews: 'نئی آراء',
    unread_alerts: 'بغیر پڑھے ہوئے الرٹس',
    monthly_bookings_revenue: 'ماہانہ بکنگ اور آمدنی',
    booking_status_dist: 'بکنگ کی حالت کی تقسیم',
    system_catalog_settings: 'سسٹم کیٹلاگ کی ترتیبات',
    manage_metadata_catalogs: 'گاڑیوں کے برانڈز، سروسز اور کوریج زونز کے لیے میٹا ڈیٹا کیٹلاگ کا انتظام کریں',
    brands: 'برانڈز',
    models: 'ماڈلز',
    categories: 'کیٹیگریز',
    areas: 'علاقے',
    import_csv: 'سی ایس وی امپورٹ کریں',
    staff_management: 'اسٹاف مینیجمنٹ',
    staff_members_manage: 'اسٹاف ممبرز · اکاؤنٹس اور شیڈولنگ کا انتظام کریں',
    create_account_directly: 'براہ راست اکاؤنٹ بنائیں',
    dashboard_back: 'ڈیش بورڈ',
    current_staff: 'موجودہ اسٹاف',
    schedule: 'شیڈول',
    deactivate: 'غیر فعال کریں',
    invite_new_helper: 'نیا مددگار مدعو کریں',
    send_invitation_link: 'دعوت نامہ لنک بھیجیں',
    recent_invitations: 'حالیہ دعوت نامے',
    add_new_helper: 'نیا مددگار / اسٹاف اکاؤنٹ شامل کریں',
    create_internal_credentials: 'فیلڈ ہیلپرز یا آپریشنز عملے کے لیے اندرونی اسناد بنائیں',
    first_name: 'پہلا نام',
    last_name: 'آخری نام',
    email_address: 'ای میل ایڈریس',
    phone_number: 'فون نمبر',
    select_role: 'عہدہ منتخب کریں',
    password: 'پاس ورڈ',
    internal_notes: 'اندرونی نوٹ',
    create_staff_account: 'اسٹاف اکاؤنٹ بنائیں',
    staff_dashboard: 'اسٹاف ڈیش بورڈ',
    welcome_back: 'خوش آمدید',
    my_work: 'میرا کام',
    my_dashboard: 'میرا ڈیش بورڈ',
    all_bookings: 'تمام بکنگز',
    full_dashboard: 'مکمل ڈیش بورڈ',
    my_bookings: 'میری بکنگز',
    today: 'آج',
    messages: 'پیغامات',
    todays_schedule: 'آج کا شیڈول',
    active_jobs: 'فعال کام',
    jobs_assigned: 'تفویض کردہ کام',
    pickup_required: 'پک اپ درکار ہے'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
  };

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
