import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav & General
    home: "Home",
    insurance: "Insurance",
    roadside: "Roadside",
    scrap: "Scrap",
    dashboard: "Dashboard",
    profile: "Profile",
    requests: "Requests",
    vehicles: "Vehicles",
    get_quote: "Get Quote",
    our_services: "Services",
    find_garages: "Find Garages",
    nav_about: "About Us",
    contact_us: "Contact",
    quotes: 'My Quotes',
    invoices: 'My Invoices',
    sign_out: 'Sign Out',
    welcome: 'Welcome back to Garro',
    lang_toggle: 'العربية (RTL)',
    back_to_dashboard: "Back to Dashboard",
    edit: "Edit",
    delete: "Delete",
    status: "Status",
    actions: "Actions",
    details: "Details",
    loading: "Loading...",
    submit: "Submit",
    add: "Add",
    cancel: "Cancel",
    remove: "Remove",

    // Hero Home
    trusted_platform: "UAE's Trusted Car Service Platform",
    get_help: "Get Instant Help From Verified UAE Garages",
    hero_sub: "Emergency or regular service, we connect you with top-rated garages near you.",
    verified_garages: "Verified Garages",
    support: "Support",
    transparent: "Transparent",

    // Quote Form
    get_quotes_title: "Get Instant Quotes from Top-Rated Garages",
    quotes_sub: "Transparent pricing · Verified garages · Instant quotes",
    service_category: "Service Category",
    sub_category_label: "Sub-Category",
    brand: "Brand",
    model: "Model",
    year: "Year",
    city: "City",
    area_label: "Area",
    describe_issue: "Describe Your Issue",
    contact_info: "Contact Info",
    preferred_time: "Preferred Time",
    get_a_quote: "Get a Quote",
    select_category: "Select main category",
    select_subcategory: "Select sub-category",
    select_category_first: "Select main category first",
    select_brand_first: "Select Brand first",
    select_city_first: "Select City first",
    desc_placeholder: "Describe the issue",
    phone_placeholder: "Enter mobile number",
    select_time: "Select time",
    time_asap: "ASAP — Urgent",
    time_today: "Today",
    time_week: "This Week",
    time_flexible: "Flexible",

    // How It Works
    how_it_works: "How Garro Works",
    how_sub: "Simple steps to get your car back on track with trusted service.",
    step1_title: "Select Issue",
    step1_desc: "Tell us what your car needs.",
    step2_title: "We Search",
    step2_desc: "We find the best local garages.",
    step3_title: "Compare & Choose",
    step3_desc: "Compare prices & services.",
    step4_title: "Pick Up / Drop",
    step4_desc: "Book a slot & get your car serviced.",
    step5_title: "Track & Relax",
    step5_desc: "Live updates till your car is done.",
    get_quote_now: "Get a Quote Now",

    // Dark Stats
    stat_verified_uae: "Verified Garages Across UAE",
    stat_happy_served: "Happy Customers Served",
    stat_avg_response: "Average Response Time",
    stat_satisfaction: "Customer Satisfaction Rate",
    stat_emergency_support: "Emergency Support",

    // Profile Page
    profile_title: "My Account Profile",
    personal_info: "Personal Information",
    first_name: "First Name",
    last_name: "Last Name",
    email_readonly: "Email Address (Read-only)",
    phone_readonly: "Phone Number (Read-only)",
    save_profile_changes: "Save Profile Changes",
    change_pwd_title: "🔐 Change Account Password",
    change_pwd_desc: "Verification code will be sent to your email to confirm this action",
    current_pwd_label: "Current Account Password",
    current_pwd_placeholder: "Enter current password to request OTP",
    verify_send_otp: "Verify & Send OTP",
    enter_otp: "Enter 6-Digit Email OTP",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    new_pwd_placeholder: "Min 6 characters",
    confirm_pwd_placeholder: "Repeat new password",
    back: "Back",
    submit_pwd_change: "Confirm Password Change",
    updating: "Updating...",
    manage_fleet_title: "🚗 Manage Your Fleet",
    manage_fleet_desc: "Add your family cars or fleet vehicles here. You can select them easily when scheduling diagnostics, major services, or recovery requests.",
    security_alert_title: "⚠️ Security Protection",
    security_alert_desc: "For security, email and phone numbers cannot be changed directly. Toggling password changes requires OTP validation, and profiles lock for 30 minutes after 5 failed attempts.",
    demo_mode: "Demo Mode",
    use_code: "Use code",
    to_verify: "to verify",

    // Vehicles Page
    my_garage_title: "🚗 My Garage (Vehicles)",
    registered_vehicles: "Registered Vehicles",
    no_vehicles: "No vehicles registered yet. Add your first vehicle using the form on the right.",
    add_vehicle: "Add a Vehicle",
    brand_make: "Brand / Make",
    select_make: "Select Make",
    registration_plate: "Registration Plate",
    plate_placeholder: "e.g. Dubai A-12345",
    model_placeholder: "Select Model",
    year_placeholder: "Select Year",
    vin_placeholder: "17-digit Chassis Number",
    vin_optional: "VIN / Chassis (Optional)",
    adding_btn: "Adding Vehicle...",
    add_vehicle_btn: "Register Vehicle",
    remove_vehicle_btn: "Remove Vehicle",
    status_roadworthy: "Status: Roadworthy",

    // Requests Page
    my_service_requests: "My Service Requests",
    active_requests: "Active Requests",
    past_requests: "Past / Closed",
    all_requests: "All Requests",
    no_requests: "No service requests found.",
    request_id: "Request ID",
    date_submitted: "Date Submitted",
    garage_assigned: "Garage Assigned",
    helper_assigned: "Helper Assigned",
    track_service: "Track Service",
    unassigned: "Unassigned (Admin Review)",

    // Quotes Page
    my_service_quotes: "My Service Quotes",
    no_quotes: "No active service quotes found.",
    view_quote: "View Quote",
    approve: "Approve",
    reject: "Reject",
    total_price: "Total Price",
    vat_included: "VAT Included (5%)",
    quote_expires: "Expires In",
    expired: "Expired",
    spare_parts_cost: "Spare Parts Cost",
    labor_cost: "Labor / Repair Charges",
    aed: "AED",
    subtotal: "Subtotal",
    service_fee: "Service Fee (10%)",
    vat: "VAT (5%)",
    total_due: "Total Amount Due",
    reject_quote_btn: "Reject Quote",
    approve_quote_btn: "Approve Quote",
    request_details: "Request Details",
    quote_from: "Quote from",

    // Invoices Page
    my_service_invoices: "My Invoices & Payments",
    no_invoices: "No invoices found.",
    invoices_desc: "Download official UAE Tax Invoices and settle pending payments.",
    date: "Date",
    vehicle: "Vehicle",
    invoice_no: "Invoice No",
    amount: "Amount",
    due_date: "Due Date",
    pay_now: "Pay Now",
    download_invoice: "Download Invoice",
    payment_status: "Payment Status",
    paid: "Paid",
    unpaid: "Unpaid",

    // Footer
    footer_desc: "UAE's most trusted car help platform. Fast, reliable & certified car service across Dubai and all UAE emirates.",
    quick_links: "Quick Links",
    support_title: "Support",
    emergency_pickup: "Emergency Pickup",
    get_offers: "Get Offers & Updates",
    your_email: "Your email",
    subscribed_msg: "✓ Subscribed! Watch your inbox.",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2025 Garro · All rights reserved · UAE's Most Trusted Car Service Platform",

    // Admin Dashboard
    overview: "Overview",
    operations: "Operations",
    manage_garages: "Manage Garages",
    system_catalog: "System Catalog",
    quote_builder: "Quote Builder",
    customer_search: "Customer Search",
    complaints: "Complaints",
    bookings: "Bookings",
    people: "People",
    all_users: "All Users",
    staff_view: "Staff View",
    manage_staff: "Manage Staff",
    back_to_site: "Back to Site",
    good_morning: "Good Morning",
    happening_today: "Here's what's happening at Garro today",
    active_garages: "Active Garages",
    todays_bookings: "Today's Bookings",
    completed: "completed",
    pending: "Pending",
    month_revenue: "Month Revenue",
    this_week: "this week",
    customers: "Customers",
    staff: "staff",
    avg_rating: "Avg Rating",
    new_reviews: "new this week",
    unread_messages: "Unread Messages",
    total_bookings: "Total Bookings",
    revenue_bookings: "Revenue & Bookings — Last 6 Months",
    revenue_trend: "Completed bookings revenue trend",
    booking_status: "Booking Status",
    current_distribution: "Current distribution",
    recent_bookings: "Recent Bookings",
    view_all: "View all",

    // About Page
    about_story: "Our Story",
    about_hero_title1: "The Digital Standard for",
    about_hero_title2: "Trusted Automotive Service.",
    about_hero_desc1: "Garro began with a singular mission: to simplify vehicle care. We operate as the premium marketplace connecting car owners with transparent, upfront pricing, frictionless logistics including doorstep pickup, and comprehensive real-time updates.",
    about_hero_desc2: "Our platform currently serves Dubai and is expanding across the UAE. Whether you need diagnostics, major repairs, aesthetics, or roadside assistance — Garro has got you covered.",
    about_values_tag: "What We Stand For",
    about_values_title: "Our Values",
    about_val1_title: "Upfront, Verified Trust & Transparency",
    about_val1_1: "Detailed quote provided for services, no surprises on pricing.",
    about_val1_2: "Receive a final, transparent digital inspection report after every service.",
    about_val1_3: "View and select garages based on certified ratings and customer reviews.",
    about_val2_title: "Frictionless Dispatch & Live Logistics",
    about_val2_1: "Seamless scheduling of service times and dispatch, supported 09:00 AM – 06:00 PM (Mon–Sat).",
    about_val2_2: "Choose from Free Doorstep Pickup or Self-Drop options.",
    about_val2_3: "Track your vehicle's journey and service status through your digital portal.",
    about_val3_title: "100% Certified Garages & Handpicked Experts",
    about_val3_1: "Garro partners exclusively with Dubai's trusted car service marketplaces for unparalleled quality.",
    about_val3_2: "Every vehicle undergoes a comprehensive Digitally Scanned Inspection.",
    about_val3_3: "Trust verified, handpicked technicians with proven track records for your specific vehicle brand.",

    // Contact Page
    contact_get_in_touch: "Get In Touch",
    contact_hero_title1: "Contact",
    contact_hero_title2: "Garro",
    contact_hero_desc: "Have a question, feedback, or need support? We're here to help — 6 days a week.",
    contact_details_title: "Our Contact Details",
    contact_phone_title: "Phone",
    contact_phone_sub: "Mon–Sat, 9AM–6PM",
    contact_email_title: "Email",
    contact_email_sub: "We reply within 24 hours",
    contact_loc_title: "Location",
    contact_loc_sub: "Also serving Kerala, India",
    contact_hours_title: "Working Hours",
    contact_hours_sub: "Sunday: Closed",
    contact_follow: "Follow Us",
    contact_send_msg: "Send Us a Message",
    contact_fname: "First Name",
    contact_lname: "Last Name",
    contact_email_placeholder: "john@example.com",
    contact_phone: "Phone Number",
    contact_subject: "Subject",
    contact_subj_general: "General Inquiry",
    contact_subj_service: "Service Issue",
    contact_subj_partner: "Partnership",
    contact_subj_billing: "Billing",
    contact_subj_other: "Other",
    contact_message: "Message",
    contact_msg_placeholder: "How can we help you?",
    contact_btn_send: "Send Message",
    contact_success_title: "Message Sent!",
    contact_success_desc: "We have received your message and will get back to you within 24 hours.",

    // Services Page
    services_what_we_offer: "What We Offer",
    services_hero_title1: "Professional",
    services_hero_title2: "Car Services",
    services_hero_desc: "From a quick wash to full mechanical overhaul — Garro connects you to certified garages across the UAE.",
    services_search_placeholder: "Search services...",
    services_no_match: "No services found matching",
    services_clear_search: "Clear Search",
    service_from_aed: "From AED",
    service_book_now: "Book Now",
    services_cat_wash: "Car Wash & Cleaning",
    services_cat_wash_desc: "Premium exterior and interior cleaning services for a spotless finish.",
    services_cat_maintenance: "Regular Maintenance",
    services_cat_maintenance_desc: "Oil changes, filters, and full vehicle health checks by certified technicians.",
    services_cat_repair: "Mechanical Repairs",
    services_cat_repair_desc: "Engine, suspension, brake repairs and comprehensive diagnostics.",
    services_cat_painting: "Painting & Denting",
    services_cat_painting_desc: "Scratch removal, panel beating, and full body painting services.",
    services_cat_ac: "A/C Service",
    services_cat_ac_desc: "Gas top-up, cooling system repairs, and full A/C diagnostics.",
    services_cat_tyre: "Tyre Services",
    services_cat_tyre_desc: "Wheel alignment, balancing, rotation, and new tyre fitting.",
    services_cat_battery: "Battery Change",
    services_cat_battery_desc: "On-site battery testing, jump-start, and same-day replacement.",
    services_cat_detailing: "Car Detailing",
    services_cat_detailing_desc: "Ceramic coating, paint protection, and full interior detailing."
  },
  ar: {
    // Nav & General
    home: "الرئيسية",
    insurance: "تأمين",
    roadside: "الطريق",
    scrap: "سكراب",
    dashboard: "لوحة التحكم",
    profile: "الملف الشخصي",
    requests: "الطلبات",
    vehicles: "مركباتي",
    get_quote: "طلب تسعير",
    our_services: "خدماتنا",
    find_garages: "البحث عن كراجات",
    nav_about: "من نحن",
    contact_us: "اتصل بنا",
    quotes: 'عروض الأسعار',
    invoices: 'فواتيري',
    sign_out: 'تسجيل الخروج',
    welcome: 'مرحباً بك في قارو',
    lang_toggle: 'English (LTR)',
    back_to_dashboard: "العودة للوحة التحكم",
    edit: "تعديل",
    delete: "حذف",
    status: "الحالة",
    actions: "الإجراءات",
    details: "التفاصيل",
    loading: "جاري التحميل...",
    submit: "إرسال",
    add: "إضافة",
    cancel: "إلغاء",
    remove: "إزالة",

    // Hero Home
    trusted_platform: "منصة صيانة السيارات الأكثر ثقة في الإمارات",
    get_help: "احصل على مساعدة فورية من كراجات الإمارات المعتمدة",
    hero_sub: "خدمات الطوارئ أو الخدمات الدورية، نصلك بأفضل الكراجات تقييماً بالقرب منك.",
    verified_garages: "كراج معتمد",
    support: "الدعم الفني",
    transparent: "شفافية تامة",

    // Quote Form
    get_quotes_title: "احصل على عروض أسعار فورية من كراجات ممتازة",
    quotes_sub: "أسعار شفافة · كراجات معتمدة · عروض أسعار فورية",
    service_category: "فئة الخدمة",
    sub_category_label: "الفئة الفرعية",
    brand: "الماركة",
    model: "الموديل",
    year: "السنة",
    city: "المدينة",
    area_label: "المنطقة",
    describe_issue: "وصف المشكلة",
    contact_info: "معلومات الاتصال",
    preferred_time: "الوقت المفضل",
    get_a_quote: "احصل على عرض سعر",
    select_category: "اختر الفئة الرئيسية",
    select_subcategory: "اختر الفئة الفرعية",
    select_category_first: "اختر الفئة الرئيسية أولاً",
    select_brand_first: "اختر الماركة أولاً",
    select_city_first: "اختر المدينة أولاً",
    desc_placeholder: "صف المشكلة هنا بالتفصيل...",
    phone_placeholder: "أدخل رقم الهاتف المحمول",
    select_time: "اختر الوقت",
    time_asap: "عاجل جداً — في أسرع وقت",
    time_today: "اليوم",
    time_week: "هذا الأسبوع",
    time_flexible: "وقت مرن / غير محدد",

    // How It Works
    how_it_works: "كيف يعمل قارو",
    how_sub: "خطوات بسيطة لإصلاح سيارتك وإعادتها للطريق بخدمات موثوقة.",
    step1_title: "اختر المشكلة",
    step1_desc: "أخبرنا بما تحتاجه سيارتك.",
    step2_title: "نحن نبحث",
    step2_desc: "نبحث عن أفضل الكراجات المحلية.",
    step3_title: "قارن واختر",
    step3_desc: "قارن بين الأسعار والخدمات.",
    step4_title: "الاستلام والتوصيل",
    step4_desc: "احجز موعداً واحصل على صيانة لسيارتك.",
    step5_title: "تتبع واسترخِ",
    step5_desc: "تحديثات مباشرة حتى الانتهاء من سيارتك.",
    get_quote_now: "احصل على عرض سعر الآن",

    // Dark Stats
    stat_verified_uae: "كراج معتمد في جميع أنحاء الإمارات",
    stat_happy_served: "عميل سعيد تم خدمتهم بنجاح",
    stat_avg_response: "متوسط وقت الاستجابة",
    stat_satisfaction: "معدل رضا العملاء",
    stat_emergency_support: "دعم الطوارئ على مدار الساعة",

    // Profile Page
    profile_title: "ملف الحساب الشخصي",
    personal_info: "المعلومات الشخصية",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    email_readonly: "البريد الإلكتروني (للقراءة فقط)",
    phone_readonly: "رقم الهاتف (للقراءة فقط)",
    save_profile_changes: "حفظ تغييرات الملف الشخصي",
    change_pwd_title: "🔐 تغيير كلمة مرور الحساب",
    change_pwd_desc: "سيتم إرسال رمز التحقق إلى بريدك الإلكتروني لتأكيد هذا الإجراء",
    current_pwd_label: "كلمة المرور الحالية للحساب",
    current_pwd_placeholder: "أدخل كلمة المرور الحالية لطلب رمز التحقق",
    verify_send_otp: "التحقق وإرسال الرمز",
    enter_otp: "أدخل رمز التحقق المكون من 6 أرقام",
    new_password: "كلمة المرور الجديدة",
    confirm_new_password: "تأكيد كلمة المرور الجديدة",
    new_pwd_placeholder: "6 أحرف كحد أدنى",
    confirm_pwd_placeholder: "أعد كتابة كلمة المرور الجديدة",
    back: "رجوع",
    submit_pwd_change: "تأكيد تغيير كلمة المرور",
    updating: "جاري التحديث...",
    manage_fleet_title: "🚗 إدارة أسطول سياراتك",
    manage_fleet_desc: "أضف سيارات عائلتك أو أسطول مركباتك هنا. يمكنك اختيارهم بسهولة عند حجز الفحص، أو الصيانة، أو طلبات السحب.",
    security_alert_title: "⚠️ حماية الأمان",
    security_alert_desc: "لدواعي أمنية، لا يمكن تغيير البريد الإلكتروني وأرقام الهواتف مباشرة. يتطلب تغيير كلمة المرور التحقق من رمز OTP، ويتم قفل الملف الشخصي لمدة 30 دقيقة بعد 5 محاولات فاشلة.",
    demo_mode: "وضع التجربة",
    use_code: "استخدم الرمز",
    to_verify: "للتحقق",

    // Vehicles Page
    my_garage_title: "🚗 كراجي (المركبات)",
    registered_vehicles: "المركبات المسجلة",
    no_vehicles: "لا توجد مركبات مسجلة بعد. أضف مركبتك الأولى باستخدام النموذج على اليمين.",
    add_vehicle: "إضافة مركبة",
    brand_make: "الماركة / المصنع",
    select_make: "اختر الماركة",
    registration_plate: "لوحة الترخيص",
    plate_placeholder: "مثال: دبي A-12345",
    model_placeholder: "اختر الموديل",
    year_placeholder: "اختر السنة",
    vin_placeholder: "رقم الشاسيه المكون من 17 خانة",
    vin_optional: "رقم الشاسيه / VIN (اختياري)",
    adding_btn: "جاري الإضافة...",
    add_vehicle_btn: "تسجيل المركبة",
    remove_vehicle_btn: "إزالة المركبة",
    status_roadworthy: "الحالة: جاهزة للاستخدام",

    // Requests Page
    my_service_requests: "طلبات الصيانة الخاصة بي",
    active_requests: "الطلبات النشطة",
    past_requests: "السابقة / المغلقة",
    all_requests: "كل الطلبات",
    no_requests: "لم يتم العثور على طلبات صيانة.",
    request_id: "رقم الطلب",
    date_submitted: "تاريخ تقديم الطلب",
    garage_assigned: "الكراج المعين",
    helper_assigned: "المساعد المعين",
    track_service: "تتبع الخدمة",
    unassigned: "لم يتم التعيين بعد (تحت المراجعة)",

    // Quotes Page
    my_service_quotes: "عروض أسعار الخدمة",
    no_quotes: "لم يتم العثور على عروض أسعار نشطة.",
    view_quote: "عرض السعر",
    approve: "موافقة",
    reject: "رفض",
    total_price: "السعر الإجمالي",
    vat_included: "شامل ضريبة القيمة المضافة (5%)",
    quote_expires: "ينتهي العرض خلال",
    expired: "منتهي الصلاحية",
    spare_parts_cost: "تكلفة قطع الغيار",
    labor_cost: "أجور العمالة / الإصلاح",
    aed: "د.إ",
    subtotal: "المجموع الفرعي",
    service_fee: "رسوم الخدمة (10%)",
    vat: "ضريبة القيمة المضافة (5%)",
    total_due: "إجمالي المبلغ المستحق",
    reject_quote_btn: "رفض عرض السعر",
    approve_quote_btn: "قبول عرض السعر",
    request_details: "تفاصيل الطلب",
    quote_from: "عرض سعر من",

    // Invoices Page
    my_service_invoices: "الفواتير والمدفوعات الخاصة بي",
    no_invoices: "لم يتم العثور على فواتير.",
    invoices_desc: "تحميل فواتير ضريبة دولة الإمارات الرسمية وتسوية المدفوعات المعلقة.",
    date: "التاريخ",
    vehicle: "المركبة",
    invoice_no: "رقم الفاتورة",
    amount: "القيمة",
    due_date: "تاريخ الاستحقاق",
    pay_now: "ادفع الآن",
    download_invoice: "تحميل الفاتورة",
    payment_status: "حالة الدفع",
    paid: "مدفوعة",
    unpaid: "غير مدفوعة",

    // Footer
    footer_desc: "منصة مساعدة السيارات الأكثر موثوقية في الإمارات. خدمة سيارات سريعة وموثوقة ومعتمدة في دبي وجميع إمارات الدولة.",
    quick_links: "روابط سريعة",
    our_services: "خدماتنا",
    support_title: "الدعم",
    contact_us: "اتصل بنا",
    emergency_pickup: "نقل طوارئ",
    get_offers: "احصل على العروض والتحديثات",
    your_email: "بريدك الإلكتروني",
    subscribed_msg: "✓ تم الاشتراك بنجاح! تابع صندوق الوارد.",
    privacy: "الخصوصية",
    terms: "الشروط",
    copyright: "© 2025 غارو · جميع الحقوق محفوظة · منصة خدمات السيارات الأكثر موثوقية في الإمارات",

    // Admin Dashboard
    overview: "نظرة عامة",
    operations: "العمليات",
    manage_garages: "إدارة الكراجات",
    find_garages: "البحث عن كراجات",
    system_catalog: "كتالوج النظام",
    quote_builder: "منشئ عروض الأسعار",
    customer_search: "البحث عن العملاء",
    complaints: "الشكاوى",
    bookings: "الحجوزات",
    people: "الأشخاص",
    all_users: "جميع المستخدمين",
    staff_view: "عرض الموظفين",
    manage_staff: "إدارة الموظفين",
    back_to_site: "العودة للموقع",
    good_morning: "صباح الخير",
    happening_today: "إليك ما يحدث في قارو اليوم",
    active_garages: "الكراجات النشطة",
    todays_bookings: "حجوزات اليوم",
    completed: "مكتمل",
    pending: "قيد الانتظار",
    month_revenue: "إيرادات الشهر",
    this_week: "هذا الأسبوع",
    customers: "العملاء",
    staff: "الموظفين",
    avg_rating: "متوسط التقييم",
    new_reviews: "جديد هذا الأسبوع",
    unread_messages: "رسائل غير مقروءة",
    total_bookings: "إجمالي الحجوزات",
    revenue_bookings: "الإيرادات والحجوزات — آخر 6 أشهر",
    revenue_trend: "اتجاه إيرادات الحجوزات المكتملة",
    booking_status: "حالة الحجوزات",
    current_distribution: "التوزيع الحالي",
    recent_bookings: "الحجوزات الأخيرة",
    view_all: "عرض الكل",

    // About Page
    about_story: "قصتنا",
    about_hero_title1: "المعيار الرقمي لـ",
    about_hero_title2: "خدمات السيارات الموثوقة.",
    about_hero_desc1: "بدأت قارو بمهمة واحدة: تبسيط العناية بالسيارات. نحن نعمل كسوق إلكتروني متميز يربط أصحاب السيارات بأسعار شفافة، وخدمات نقل سلسة تشمل الاستلام من الباب، وتحديثات فورية شاملة.",
    about_hero_desc2: "تخدم منصتنا حالياً دبي ونتوسع في جميع أنحاء الإمارات. سواء كنت بحاجة إلى فحص، أو إصلاحات كبيرة، أو تجميل السيارة، أو المساعدة على الطريق — قارو توفر لك كل ما تحتاجه.",
    about_values_tag: "مبادئنا",
    about_values_title: "قيمنا",
    about_val1_title: "شفافية وثقة معتمدة وواضحة",
    about_val1_1: "تقديم عرض سعر مفصل للخدمات، لا توجد مفاجآت في الأسعار.",
    about_val1_2: "احصل على تقرير فحص رقمي شفاف ونهائي بعد كل خدمة.",
    about_val1_3: "عرض واختيار الكراجات بناءً على التقييمات المعتمدة ومراجعات العملاء.",
    about_val2_title: "لوجستيات مباشرة وإرسال سلس",
    about_val2_1: "جدولة سلسة لأوقات الخدمة والإرسال، مدعومة من 09:00 صباحاً – 06:00 مساءً (الاثنين–السبت).",
    about_val2_2: "اختر بين الاستلام المجاني من الباب أو التسليم الشخصي.",
    about_val2_3: "تتبع رحلة مركبتك وحالة الخدمة من خلال بوابتك الرقمية.",
    about_val3_title: "كراجات معتمدة 100% وخبراء مختارون",
    about_val3_1: "تتعاون قارو حصرياً مع أسواق خدمات السيارات الموثوقة في دبي لضمان جودة لا مثيل لها.",
    about_val3_2: "تخضع كل مركبة لفحص رقمي شامل.",
    about_val3_3: "ثق بالفنيين المعتمدين والمختارين بعناية مع سجل حافل لعلامة سيارتك المحددة.",

    // Contact Page
    contact_get_in_touch: "تواصل معنا",
    contact_hero_title1: "اتصل",
    contact_hero_title2: "بقارو",
    contact_hero_desc: "لديك سؤال، ملاحظات، أو تحتاج إلى دعم؟ نحن هنا للمساعدة — 6 أيام في الأسبوع.",
    contact_details_title: "تفاصيل الاتصال بنا",
    contact_phone_title: "الهاتف",
    contact_phone_sub: "الاثنين–السبت، 9ص–6م",
    contact_email_title: "البريد الإلكتروني",
    contact_email_sub: "نرد خلال 24 ساعة",
    contact_loc_title: "الموقع",
    contact_loc_sub: "نخدم أيضاً كيرالا، الهند",
    contact_hours_title: "ساعات العمل",
    contact_hours_sub: "الأحد: مغلق",
    contact_follow: "تابعنا",
    contact_send_msg: "أرسل لنا رسالة",
    contact_fname: "الاسم الأول",
    contact_lname: "اسم العائلة",
    contact_email_placeholder: "john@example.com",
    contact_phone: "رقم الهاتف",
    contact_subject: "الموضوع",
    contact_subj_general: "استفسار عام",
    contact_subj_service: "مشكلة في الخدمة",
    contact_subj_partner: "شراكة",
    contact_subj_billing: "فواتير",
    contact_subj_other: "أخرى",
    contact_message: "الرسالة",
    contact_msg_placeholder: "كيف يمكننا مساعدتك؟",
    contact_btn_send: "إرسال الرسالة",
    contact_success_title: "تم إرسال الرسالة!",
    contact_success_desc: "لقد تلقينا رسالتك وسنرد عليك خلال 24 ساعة.",

    // Services Page
    services_what_we_offer: "ماذا نقدم",
    services_hero_title1: "خدمات سيارات",
    services_hero_title2: "احترافية",
    services_hero_desc: "من غسيل سريع إلى إصلاح ميكانيكي شامل — تربطك قارو بالكراجات المعتمدة في جميع أنحاء الإمارات.",
    services_search_placeholder: "البحث عن خدمات...",
    services_no_match: "لم يتم العثور على خدمات مطابقة",
    services_clear_search: "مسح البحث",
    service_from_aed: "تبدأ من د.إ",
    service_book_now: "احجز الآن",
    services_cat_wash: "غسيل وتنظيف السيارات",
    services_cat_wash_desc: "خدمات تنظيف خارجية وداخلية متميزة لسيارة ناصعة النظافة.",
    services_cat_maintenance: "الصيانة الدورية",
    services_cat_maintenance_desc: "تغيير الزيت، الفلاتر، وفحوصات شاملة للسيارة من قبل فنيين معتمدين.",
    services_cat_repair: "إصلاحات ميكانيكية",
    services_cat_repair_desc: "إصلاح المحرك، نظام التعليق، الفرامل وفحص شامل للأعطال.",
    services_cat_painting: "صبغ وسمكرة",
    services_cat_painting_desc: "إزالة الخدوش، إصلاح الهيكل، وخدمات صبغ السيارة بالكامل.",
    services_cat_ac: "خدمة التكييف",
    services_cat_ac_desc: "تعبئة غاز، إصلاح نظام التبريد، وفحص شامل للتكييف.",
    services_cat_tyre: "خدمات الإطارات",
    services_cat_tyre_desc: "ميزانية العجلات، الترصيص، التبديل، وتركيب إطارات جديدة.",
    services_cat_battery: "تبديل البطارية",
    services_cat_battery_desc: "فحص البطارية في الموقع، تشغيل سريع، واستبدال في نفس اليوم.",
    services_cat_detailing: "تلميع وعناية فائقة",
    services_cat_detailing_desc: "طبقة نانو سيراميك، حماية الطلاء، وتلميع داخلي شامل."
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
  };

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
